### ISSUE TITLE
dcos-docker muti cluster

### ISSUE THREAD

**Issue by xyjwsj** [dcos/dcos-e2e#1045]
Docker Env, Not in same machine, I want to create most masters and agents, I dont not how to do.
In document, I know how to create in same machine, but Not in same machine?

**Comment by xyjwsj** [comment]
Yeah,@adamtheturtle
I‘m using the DC/OS E2E CLI.
I‘m using the dcos-docker create command.
I want to use it for multiple machine clusters, not stand-alone.

**Comment by adamtheturtle** [comment]
@xyjwsj Thank you for clarifying.

That is not currently supported.

What is your use case? Knowing this might help us know whether to prioritise this.

**Comment by jgehrcke** [comment]
In addition to what @adamtheturtle asked I would like to clarify that if your goal is to run DC/OS on multiple machines then canonical installation of DC/OS is the right way to go, and `dcos-docker` is not.

`dcos-docker` (DC/OS E2E with the Docker backend) can be thought of as a convenient way to "simulate running a real DC/OS cluster on a single machine".

**Comment by xyjwsj** [comment]
Could support this mode? I need run DC/OS on  multiple machines, how to do?

**Comment by adamtheturtle** [comment]
There are multiple ways to install DC/OS on multiple nodes.
See https://docs.mesosphere.com/1.11/installing/oss/.
I do not think that DC/OS E2E (and DC/OS in Docker) is the way to go - it is not supported for this use case.
I would follow the instructions in the above link.
However - is there a particular reason you want to use DC/OS E2E?

**Comment by adamtheturtle** [comment]
@xyjwsj I will close this - please re-open or open a new issue if you are still having trouble.
