### ISSUE TITLE
DC/OS services close connections periodically

### ISSUE THREAD

**Issue by romancardenas** [dcos/dcos-e2e#1058]
Hello everyone!

First, I want to apologise, cause I am quite noob in DC/OS (perhaps this question is stupid). But let's put you into context:

- I have installed a DC/OS E2E (v1.11) cluster in a CentOS 7 machine.
- The host CentOS machine has an IP address that complies with the LAN mask.
- The cluster, however, has its own IP addresses (172.0.17.1/16), which coincides with the docker0 network interface of the host machine.
- I have configured the network for redirecting any connection to 172.0.17.1/16 to the host machine, and this host machine forwards satisfactorily the packets.
- I have deployed in the cluster the following services: Kafka, Cassandra, MongoDB and an EMQ MQTT broker.

When using ANY of these services from an external machine, it works fine until the connection is closed every 50 seconds, more or less. I could not find the reason to this disconnection, but I tried the following:

Setting the services using docker containers in the host machine: Connections are not closed
Running service clients in the DC/OS cluster: Connections are not closed.

I think that the problem is related with the docker0 network interface configuration of the host machine, but I was not able to find the issue.

Any help is welcome. Thank you in advance.

**Comment by timaa2k** [comment]
Hey @romancardenas!
First of all thanks for filing this issue, your use case could be really valuable for the development of `dcos-e2e` and I'm eager trying to help you out. Could you please elaborate on:
* Your exact use-case of DC/OS E2E. E2E is meant to be a tool for developing and testing DC/OS, it is not meant to set up a production environment.
* Did you use the DC/OS E2E CLI or the Python library?
We've recently added custom Docker networking support for the Python library, however this change has not made it into the CLI yet.
* How exactly did you configure the network for redirecting the connections to 172.17.0.1/16?

//Tim

**Comment by timaa2k** [comment]
Thank you @romancardenas.
This is not a use case that we have tried ourselves, but it is valuable and we would like to help you.
Our next steps are to reproduce what you are seeing, and then we can go from there.
I will keep this issue up to date and share information with you.

**Comment by romancardenas** [comment]
Thank you very much. I will check it

**Comment by romancardenas** [comment]
It seems to work well, thanks for the support!!

**Comment by adamtheturtle** [comment]
That's great to hear.

Thank you @timaa2k for the investigation and thank you @romancardenas for your perseverance and for getting back to us.

**Comment by timaa2k** [comment]
Glad I could help :)

**Comment by adamtheturtle** [comment]
@romancardenas We have first classed that functionality and it is now even simpler.

See http://dcos-e2e.readthedocs.io/en/latest/dcos-docker-cli.html#using-a-custom-docker-network for details.
