### ISSUE TITLE
set volume to DC/OS E2E for re-running without loosing services

### ISSUE THREAD

**Issue by romancardenas** [dcos/dcos-e2e#1100]
Hi everyone!
I am trying different features of DC/OS, and I decided to user DC/OS E2E for this purpose.
As I sometimes need to run the DC/OS cluster on my laptop, I would like to assign a volume when creating the cluster, so, for following attempts, the cluster would have the same services and data. Is it possible with this product?

Thank you very much.

**Comment by adamtheturtle** [comment]
Hello @romancardenas.

This is not currently possible.

It may or may not be possible in the future.

DC/OS was designed as enterprise software running at scale. I believe that what you need is checkpointing functionality in the cluster - a way to shutdown and restore the whole DC/OS cluster and any given time. 

Some reasons why it would not work right now, or just with small amount of effort:
* Right now DC/OS E2E creates new volumes for each node's data - this would have to be changed
* The DC/OS configuration includes the IP addresses of all nodes, so we would need to preserve these
* This is something that we have not tried so I imagine that there would be multiple technical issues

I will close this issue and keep you in mind if we choose to support this in the future. However, it would be a large project.

Feel free to get in touch with us here if you have any more issues or feature requests.

Thank you,
Adam Dangoor
