### ISSUE TITLE
Unit test fails on macOS with Docker backend.

### ISSUE THREAD

**Issue by jieyu** [dcos/dcos-e2e#1139]
Since the default transport is ssh, and on macOS, there's a know issue that the container is not directly reachable from the host (no docker0 bridge).

We should consider switch to use docker-exec transport for tests related to Docker backend.

**Comment by adamtheturtle** [comment]
Some unit tests will always fail on macOS without the VPN running.
In particular, those which test the SSH transport on Docker.

That said, the `docker exec` transport is now a little battle-tested.
I think that we can make it the default transport for the Docker backend and the CLI.
This will mean that more tests will pass on macOS without the VPN.

I also see no value in the `--transport` option existing on the CLI - `docker-exec` all the way.

For now, if you want to run unit tests, use the VPN 😄

**Comment by adamtheturtle** [comment]
I changed the default transport to `docker-exec` in https://github.com/dcos/dcos-e2e/pull/1142, so I am closing this. Reopen if you think that this is not resolved.
