### ISSUE TITLE
Update for release 2018.07.30.0 Changes Causes TeamCity Failures?

### ISSUE THREAD

**Issue by bernadinm** [dcos/dcos-e2e#1278]
Hi Adam,

We are having issues building from the github.com/dcos/dcos PRs and it looks like the test fails due to the changes that was added here recently: https://github.com/dcos/dcos-e2e/commit/791cc2ce388e5201d8e42b5b489246cf53549dd7

You can see the history of the recent changes that causes the fails and wanted to know if you happen know if we can confirm.

 https://teamcity.mesosphere.io/viewType.html?buildTypeId=DcOs_Open_Test_DcosDocker_ProofOfConceptDcOsE2eDockerIntegrationTests&tab=buildTypeHistoryList&branch_DcOs_Open_Test_DcosDocker=__all_branches__

Thank you for your help!

**Comment by adamtheturtle** [comment]
@bernadinm Thank you for reporting this. The issue was the release of `msrestazure==0.5.0` which broke the dependency tree.

We are working on this as tracked by https://jira.mesosphere.com/browse/DCOS-40131.
