### ISSUE TITLE
minidcos docker doctor fails on mac osx 10.11.6

### ISSUE THREAD

**Issue by jbrinnand** [dcos/dcos-e2e#1578]
**Background - new installation of minidcos**
- mac OSX -  El Capitan 10.11.6
- minidcos, version 2019.01.05.0
- docker-machine version 0.14.0, build 89b8332
- Docker version 17.06.0-ce, build 02c1d87

**minidcos  docker doctor** 
.....

```
Error: There was an unknown error when performing a doctor check.                                                                                                       
The doctor function was "_check_systemd".
The error was: "400 Client Error: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /sys/fs/cgroup/systemd")".
9/13 checks complete: █████████████████████████████████████████████████████████████████████████████████████████████████████                                             Exception ignored in: <function tqdm.__del__ at 0x10fc51d90>
Traceback (most recent call last):
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/usr/local/Cellar/minidcos/2019.01.05.0/libexec/lib/python3.7/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

Why is this occurring? And I I don't have this mount point in docker-machine, what must be done to make minidcos docker doctor to go past this point?

**Comment by adamtheturtle** [comment]
Thank you for the report!

The only testing that has been done on macOS is with [Docker for Mac](https://docs.docker.com/docker-for-mac/install/) rather than docker-machine.

That said, see https://github.com/dcos/dcos-e2e/issues/1248 the issue which refers to removing the requirement for `/sys/fs/cgroup` to exist. No guarantees but let's follow that issue and I will try to push it forward.

**Comment by adamtheturtle** [comment]
Today's release will remove the requirement for `/sys/fs/cgroup` to exist and so I am closing this. I hope that you get further but there are no guarantees on macOS 1.11.X.
