### ISSUE TITLE
Q: why have shown more memory than physically existing? - ?cause for possible confusion?

### ISSUE THREAD

**Issue by RogerWeihrauch** [dcos/dcos-e2e#1622]
Hi to all.
Question:
Why is there more memory shown that there is physically available for the (newly) created cluster? E.g. this confuses (especially me  ;-)  ) on possibility for running/installing new necessary apps, but system informations show me that it is already swapping/cannot bring up the new app due to lack of necessary system resources (esp. necessary ram for memory)/killing processes by OOM mechanism.
In my eyes the system information on its resources is not very trustworthy at this point.
What do you all think about this? Or do I do something wrong during setting up the cluster?

Thank you all for your explanations on this.

Kind regards,
Roger.

**Comment by adamtheturtle** [comment]
Hi @RogerWeihrauch , thank you for the question.

Is it the case that each node shows the total amount of memory available to the cluster?

If so, this is a limitation of Docker, or the DC/OS interaction with Docker - each node *does* have that memory available to it, but it is shared.

**Comment by RogerWeihrauch** [comment]
@adamtheturtle 
Thank you for your response. Well; it seems some kind of confusing to me if there is only 128GB of RAM, but shown more in each cluster member. nevertheless; I will close this issue and ignore this confusion.
Regards,
Roger

**Comment by adamtheturtle** [comment]
I'm going to reopen this so that it can serve as a prompt to document this oddity. You are right that it is confusing but I think that there is no great way for this current UI to display the reality, and the UI is not going to be optimised for a Docker cluster.

**Comment by adamtheturtle** [comment]
This confusing property was documented in #1758.
