### ISSUE TITLE
Is there a way to halt all the running nodes including master in minidcos?

### ISSUE THREAD

**Issue by rajcspsg** [dcos/dcos-e2e#1669]
Vagrant provides option to stop the VM using `vagrant suspend --all` and docker provides similar option by `docker stop`.

Is there a way to halt all the running nodes including master in minidcos. 

I have checked this [link](https://buildmedia.readthedocs.org/media/pdf/minidcos/latest/minidcos.pdf). 

But couldn't find the same.

**Comment by adamtheturtle** [comment]
Thank you @rajcspsg . This is a valid feature request but I'm going to close it in favour of #1618.

**Comment by rajcspsg** [comment]
Thanks @adamtheturtle. I didn't notice there is already an issue created for this.
I will keep an eye on this.
