### ISSUE TITLE
Q:Did I miss sth.? How to create user for DCOS Master login via ssh

### ISSUE THREAD

**Issue by RogerWeihrauch** [dcos/dcos-e2e#1755]
Dear all
Since using minidcos for cluster deployment I am (no longer) able to log into the master/agents via SSH to get onto clusters' OS Shell/CLI. How do I set user/pswd for clusterwide logging in after/before deployment?
Or, did I miss sth. in the latest minidcos documentation? Or, which are user/pswd combinations to login?
Sorry for this dump Q, but in any way I am lost in this thing.
Thank you all for your helpful response.

Kind regards,
Roger

**Comment by RogerWeihrauch** [comment]
Or, where can I find additional documentation on this?

**Comment by adamtheturtle** [comment]
@RogerWeihrauch Thanks for the question.

There are multiple ways to get into the shell on a node.

First, with the `run` command:

```
$ minidcos docker run bash
[master-0]# exit
$
```

You can also use the `inspect` command to find the IP addresses, SSH default user and SSH key path.

Please let us know if that is not enough information - or close this if this resolves your issue.

**Comment by RogerWeihrauch** [comment]
@adamtheturtle 
Many thanks for your prompt and helpful support. Your hint solved my issue.
So, this one is solved from my side and I will close it.
Regards,
Roger
