### ISSUE TITLE
Installation steps improvement

### ISSUE THREAD

**Issue by Alwinius** [dcos/dcos-e2e#1810]
I was trying to install minidcos from a pretty clean Linux Mint 19.1, but there were a few instructions missing in the documentation. I imagine this could be the same in a clean Ubuntu 18.04. When I ran `sudo apt upgrade -y gcc python3-dev python3.6-dev libssl-dev` I got 
```The following packages have unmet dependencies:
 libssl-dev : Conflicts: libssl1.0-dev but 1.0.2n-1ubuntu5.3 is to be installed
 libssl1.0-dev : Conflicts: libssl-dev but 1.1.0g-2ubuntu4.3 is to be installed
E: Broken packages
```
So I only installed `gcc python3-dev python3.6-dev`. On the next step pip3 was missing, so I installed `python3-pip`. Then I could run `sudo pip3 install --upgrade git+https://github.com/dcos/dcos-e2e.git@2019.06.03.0` but got `ModuleNotFoundError: No module named 'setuptools'` so I had to install setuptools with `pip3 install setuptools`.

**Comment by adamtheturtle** [comment]
Thanks - I have now installed E2E in a Linux mint Docker container and in #1811 I added all requirements.
