### ISSUE TITLE
Travis CI builds failures

### ISSUE THREAD

**Issue by ipolyzos** [dcos/dcos-e2e#1875]
Travis CI builds failures on [Build #3274](https://travis-ci.org/dcos/dcos-e2e/builds/659569896?utm_medium=notification&utm_source=github_status) and [Build #3242](https://travis-ci.org/dcos/dcos-e2e/builds/646487035?utm_medium=notification&utm_source=github_status])

> build succeeded.
> Look for any errors in the above output or in build/linkcheck/output.txt
> The name of the builder is: linkcheckmake[1]: Leaving directory '/home/travis/build/dcos/dcos-e2e/docs/cli'
> mypy *.py src/ tests/ admin/
> +mypy setup.py versioneer.py src/ tests/ admin/
> pip-extra-reqs src/
> +pip-extra-reqs src/
> Traceback (most recent call last):
>   File "/home/travis/virtualenv/python3.5.6/bin/pip-extra-reqs", line 5, in <module>
>     from pip_check_reqs.find_extra_reqs import main
>   File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pip_check_reqs/find_extra_reqs.py", line 10, in <module>
>     from pip_check_reqs import common
>   File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/pip_check_reqs/common.py", line 10, in <module>
>     from pip._internal.download import PipSession
> ImportError: No module named 'pip._internal.download'
> lint.mk:35: recipe for target 'pip-extra-reqs' failed
> make: *** [pip-extra-reqs] Error 1
> Traceback (most recent call last):
>   File "admin/run_script.py", line 36, in <module>
>     subprocess.check_call(['make', 'lint'])
>   File "/opt/python/3.5.6/lib/python3.5/subprocess.py", line 271, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['make', 'lint']' returned non-zero exit status 2
> The command "python admin/run_script.py" exited with 1.
> cache.2
> store build cache
>

**Comment by adamtheturtle** [comment]
This is due to https://github.com/r1chardj0n3s/pip-check-reqs/pull/22 and can be remedied by using `pip-check-reqs-pip-gte-20` rather than `pip-check-reqs`.
