### ISSUE TITLE
i have a problem with minidcos when i creating cluster by vagrant

### ISSUE THREAD

**Issue by ghazl** [dcos/dcos-e2e#1877]
i followed this steps : https://minidcos.readthedocs.io/en/latest/dcos-vagrant-cli.html and i reached to creating a cluster with this command : minidcos vagrant create ./dcos_generate_config.sh then this error appear to me : The following SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed!

yum install -y centos-release

Stdout from the command:

Loaded plugins: fastestmirror

Stderr from the command:

https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found Trying other mirror. To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

One of the configured repositories failed (Docker Repository), and yum doesn't have enough cached data to continue. At this point the only safe thing yum can do is fail. There are a few ways to work "fix" this:

 1. Contact the upstream for the repository and get them to fix the problem.

 2. Reconfigure the baseurl/etc. for the repository, to point to a working
    upstream. This is most often useful if you are using a newer
    distribution release than is supported by the repository (and the
    packages for the previous distribution release still work).

 3. Run the command with the repository temporarily disabled
        yum --disablerepo=dockerrepo ...

 4. Disable the repository permanently, so yum won't use it by default. Yum
    will then just ignore the repository until you permanently enable it
    again or use --enablerepo for temporary usage:

        yum-config-manager --disable dockerrepo
    or
        subscription-manager repos --disable=dockerrepo

 5. Configure the failing repository to be skipped, if it is unavailable.
    Note that yum will try to contact the repo. when it runs most commands,
    so will have to try and fail each time (and thus. yum will be be much
    slower). If it is a very temporary problem though, this is often a nice
    compromise:

        yum-config-manager --save --setopt=dockerrepo.skip_if_unavailable=true

failure: repodata/repomd.xml from dockerrepo: [Errno 256] No more mirrors to try. https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

Error creating cluster. Full error: Command '['/usr/bin/vagrant', 'up']' returned non-zero exit status 1.

hope someone help me

**Comment by jongiddy** [comment]
Thanks for the report.

The broken image has been updated. You can now run with the flag `--vagrant-box-version '~>0.10'` to use the fixed image.  e.g. `minidcos vagrant create --vagrant-box-version '~>0.10' ./dcos_generate_config.sh`

This will become the default in a future version of `minidcos`.
