### ISSUE TITLE
DC/OS Poststart Checks & DC/OS Calico Node (felix): always fails/never get status '0' (zero); latest dcos installer

### ISSUE THREAD

**Issue by RogerWeihrauch** [dcos/dcos-e2e#1901]
Hi all
While creating/running a DCOS cluster via minidcos and docker, I always get the following message an all nodes:
![image](https://user-images.githubusercontent.com/15932486/109640462-cd7c2f00-7b50-11eb-882e-4c36f0b1b125.png)
So, do they depend on each other?
If so could be the reason that ip6table-save command is not successful on all nodes?
How to install/setup/activate ip6tables on all nodes after cluster creating w/ minidcos?

Thank you very much for your help on this issue.
Kind regards,
Roger

**Comment by jongiddy** [comment]
It may have to do with IP6, but we would need journald log files from the nodes to confirm. Poststart checks is almost certainly complaining because Calico is not happy.

Try running `sudo modprobe ip6_tables` on your host before creating the cluster. You only need to run this on your host machine, not on the cluster nodes.

**Comment by RogerWeihrauch** [comment]
Hello jongiddy
Thanks very much for our hint. But, meanwhile I had to set it up new again, so the same error still occurs. Also, Do  you have a clue on how to install minidcos newly with this command:
curl --fail -L https://github.com/|github-owner|/|github-repository|/releases/download/|release|/minidcos -o /usr/local/bin/minidcos && chmod +x /usr/local/bin/minidcos
since I do not have the relevant parts of this path? (all entries in beween the  '| |')
What is the repo called?
How to find the latest release?
Regards,
Roger

**Comment by RogerWeihrauch** [comment]
Hello jongiddy
Your hint on doing a 'modprobe ip6_tables' did the trick. DCOS comes up much faster and without described errors on calico.
So, will it be also necessary to do enable ip6_forward in /etc/systemctl.conf?
Regards
Roger

**Comment by RogerWeihrauch** [comment]
Will close this one, regardless to my open questions.
Thank you for your help.
It was highly appreciated.
Regards,
Roger
